/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CidadeDAO;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cidade;

/**
 *
 * @author 181720019
 */
public class ListCidades extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListCidades
     */
    public JDesktopPane jdpTelaInicial;
    
 
    
    public ListCidades(JDesktopPane jdpPainel) {
        initComponents();
        carregarTabela();
        this.jdpTelaInicial = jdpPainel;
    }
    
    public void carregarTabela(){
        List<Cidade> lista = CidadeDAO.getCidades();
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"Código" , "Nome da Cidade", "Estado"};
        model.setColumnIdentifiers(colunas);
        
        for (Cidade cid : lista) {
            Object[] linha = {
                cid.getCodigo(),
                cid.getNome(),
                cid.getEstado().getNome()
            };
            model.addRow( linha );
        }
        tableCidades.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCidades = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lista de Cidades");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Cidades");

        tableCidades.setBackground(new java.awt.Color(153, 153, 153));
        tableCidades.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Porto Alegre"},
                {"2", "Santa Cruz do Sul"},
                {"3", "Florianópolis"},
                {"4", "São Paulo"}
            },
            new String [] {
                "Código", "Nome da Cidade"
            }
        ));
        jScrollPane1.setViewportView(tableCidades);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(112, 112, 112)
                        .addComponent(btnEditar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tableCidades.getSelectedRow();
        if (linha<0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar uma cidade!");       
        }else{
            int codigo = (int) tableCidades.getValueAt(linha, 0);
            FrmCidade tela = new FrmCidade(codigo);
            jdpTelaInicial.add(tela);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tableCidades.getSelectedRow();
        if(linha<0){
            JOptionPane.showMessageDialog(this,"Você deve selecionar uma cidade!");
        }else{
            int codigo = (int)tableCidades.getValueAt(linha,0);
            String nome = (String)tableCidades.getValueAt(linha,1);
            
            int resposta = JOptionPane.showConfirmDialog(this,
                    "Confirma a exclusão da cidade"+ nome,
                    "Excluir Cidade", JOptionPane.YES_NO_OPTION);
            if(resposta == JOptionPane.YES_NO_OPTION){
            Cidade cidade = new Cidade();
            cidade.setCodigo(codigo);
            CidadeDAO.excluir(cidade);
            carregarTabela();
        }
       
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCidades;
    // End of variables declaration//GEN-END:variables
}
